apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: loki-values
    files:
      - values.yaml=loki-values.yaml
    options:
      disableNameSuffixHash: true  # AGGIUNTO: questo rimuove  l'hash