apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../base/monitoring/kube-state-metrics

patches:
  - target:
      kind: HelmRelease
      name: kube-state-metrics
    path: patches/values-patch.yaml
