apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/monitoring/alloy
- ingressroute.yaml
- secret.yaml

configMapGenerator:
  - name: alloy-config
    files:
      - config.alloy
    options:
      disableNameSuffixHash: true
