apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/monitoring/mimir

configMapGenerator:
  - name: mimir-config
    files:
      - mimir.yaml
    options:
      disableNameSuffixHash: true

patchesStrategicMerge:
  - mimir-helmrelease-patch.yaml