apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/monitoring/grafana
  - apisix-route.yaml
  - ingressroute.yaml
  
configMapGenerator:
  - name: grafana-values
    files:
      - values.yaml=grafana-values.yaml


